services:
  - type: web
    name: instacart-customer-segmentation
    runtime: docker
    plan: free
    branch: main
    autoDeployTrigger: commit
    healthCheckPath: /_stcore/health
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
